AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Go-Gin

  Sample SAM Template for Go-Gin

Globals:
  Function:
    Timeout: 5

Resources:
  GinFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 512
      Events:
        APIEvent:
          Type: HttpApi
      Environment:
        Variables:
          AWS_REGION: '{{resolve:ssm:LAMBDA_AWS_REGION:1}}'
          AWS_ACCESS_KEY_ID: '{{resolve:ssm:LAMBDA_AWS_ACCESS_KEY_ID:1}}'
          AWS_SECRET_ACCESS_KEY: '{{resolve:ssm:LAMBDA_AWS_SECRET_ACCESS_KEY:1}}'
    Metadata:
      DockerTag: v1
      DockerContext: .
      Dockerfile: ./docker/http-server.Dockerfile

Outputs:
  GinApi:
    Description: "API Gateway endpoint URL for Prod stage for Gin function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
