AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Go-Gin

  Sample SAM Template for Go-Gin

Globals:
  Function:
    Timeout: 5

Resources:
  GinFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 512
      Events:
        APIEvent:
          Type: HttpApi
      Environment:
        Variables:
          CONFIG_REGION: "{{resolve:ssm:/lambda/config/region:1}}"
          CONFIG_ACCESS_KEY_ID: "{{resolve:ssm:/lambda/config/access_key_id:1}}"
          CONFIG_SECRET_ACCESS_KEY: "{{resolve:ssm:/lambda/config/secret_access_key:1}}"
          DYNAMIC_LOCAL: "{{resolve:ssm:/lambda/dynamic/local:1}}"
          DYNAMIC_REMOTE: "{{resolve:ssm:/lambda/dynamic/remote:1}}"
          RUNTIME: "{{resolve:ssm:/lambda/runtime:1}}"
    Metadata:
      DockerTag: v1
      DockerContext: .
      Dockerfile: ./docker/http-server.Dockerfile

Outputs:
  GinApi:
    Description: "API Gateway endpoint URL for Prod stage for Gin function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
