AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Go-Gin

  Sample SAM Template for Go-Gin

Globals:
  Function:
    Timeout: 5

Resources:
  GinFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - S3ReadPolicy:
            BucketName: "{{resolve:ssm:/lambda/go/dynamic/s3-bucket:1}}"
      PackageType: Image
      MemorySize: 512
      Events:
        APIEvent:
          Type: HttpApi
      Environment:
        Variables:
          GO_DYNAMIC_LOCAL: "{{resolve:ssm:/lambda/go/dynamic/local:1}}"
          GO_DYNAMIC_REMOTE: "{{resolve:ssm:/lambda/go/dynamic/remote:1}}"
    Metadata:
      DockerTag: v1
      DockerContext: .
      Dockerfile: ./docker/http-server.Dockerfile

Outputs:
  GinApi:
    Description: "API Gateway endpoint URL for Prod stage for Gin function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
