// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.1
// source: sqs/sqs.proto

package sqs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestSqsId  string                 `protobuf:"bytes,1,opt,name=request_sqs_id,json=requestSqsId,proto3" json:"request_sqs_id,omitempty"`
	ResponseSqsId string                 `protobuf:"bytes,2,opt,name=response_sqs_id,json=responseSqsId,proto3" json:"response_sqs_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_sqs_sqs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_sqs_sqs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_sqs_sqs_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetRequestSqsId() string {
	if x != nil {
		return x.RequestSqsId
	}
	return ""
}

func (x *Request) GetResponseSqsId() string {
	if x != nil {
		return x.ResponseSqsId
	}
	return ""
}

func (x *Request) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Request) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Request) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestSqsId  string                 `protobuf:"bytes,1,opt,name=request_sqs_id,json=requestSqsId,proto3" json:"request_sqs_id,omitempty"`
	ResponseSqsId string                 `protobuf:"bytes,2,opt,name=response_sqs_id,json=responseSqsId,proto3" json:"response_sqs_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_sqs_sqs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_sqs_sqs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_sqs_sqs_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetRequestSqsId() string {
	if x != nil {
		return x.RequestSqsId
	}
	return ""
}

func (x *Response) GetResponseSqsId() string {
	if x != nil {
		return x.ResponseSqsId
	}
	return ""
}

func (x *Response) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Response) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_sqs_sqs_proto protoreflect.FileDescriptor

const file_sqs_sqs_proto_rawDesc = "" +
	"\n" +
	"\rsqs/sqs.proto\x12\x03sqs\"\xac\x01\n" +
	"\aRequest\x12$\n" +
	"\x0erequest_sqs_id\x18\x01 \x01(\tR\frequestSqsId\x12&\n" +
	"\x0fresponse_sqs_id\x18\x02 \x01(\tR\rresponseSqsId\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"\xaf\x01\n" +
	"\bResponse\x12$\n" +
	"\x0erequest_sqs_id\x18\x01 \x01(\tR\frequestSqsId\x12&\n" +
	"\x0fresponse_sqs_id\x18\x02 \x01(\tR\rresponseSqsId\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05errorB#Z!github.com/aura-studio/lambda/sqsb\x06proto3"

var (
	file_sqs_sqs_proto_rawDescOnce sync.Once
	file_sqs_sqs_proto_rawDescData []byte
)

func file_sqs_sqs_proto_rawDescGZIP() []byte {
	file_sqs_sqs_proto_rawDescOnce.Do(func() {
		file_sqs_sqs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sqs_sqs_proto_rawDesc), len(file_sqs_sqs_proto_rawDesc)))
	})
	return file_sqs_sqs_proto_rawDescData
}

var file_sqs_sqs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sqs_sqs_proto_goTypes = []any{
	(*Request)(nil),  // 0: sqs.Request
	(*Response)(nil), // 1: sqs.Response
}
var file_sqs_sqs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sqs_sqs_proto_init() }
func file_sqs_sqs_proto_init() {
	if File_sqs_sqs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sqs_sqs_proto_rawDesc), len(file_sqs_sqs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sqs_sqs_proto_goTypes,
		DependencyIndexes: file_sqs_sqs_proto_depIdxs,
		MessageInfos:      file_sqs_sqs_proto_msgTypes,
	}.Build()
	File_sqs_sqs_proto = out.File
	file_sqs_sqs_proto_goTypes = nil
	file_sqs_sqs_proto_depIdxs = nil
}
